# Generated by Django 3.1.4 on 2021-02-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_emailsubscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailSubscribers',
            new_name='EmailSubscriber',
        ),
    ]
