# Generated by Django 3.1.4 on 2021-02-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210206_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsourcing',
            name='gdpr_aggrement',
            field=models.BooleanField(default=False),
        ),
    ]
