# Generated by Django 3.1.4 on 2021-02-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210223_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsourcing',
            name='gdpr_aggrement',
            field=models.BooleanField(),
        ),
    ]
