# Generated by Django 3.1.4 on 2021-02-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20210223_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carsourcing',
            old_name='gdpr_aggrement',
            new_name='gdpr_agreement',
        ),
    ]
