# Generated by Django 3.1.4 on 2021-02-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20210223_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsourcing',
            name='gdpr_agreement',
        ),
    ]
