# Generated by Django 3.1.4 on 2021-01-31 02:52

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to=blog.models.BlogPost.upload_photo_to),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo_10',
            field=models.ImageField(blank=True, upload_to=blog.models.BlogPost.upload_photo_to),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to=blog.models.BlogPost.upload_photo_to),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to=blog.models.BlogPost.upload_photo_to),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to=blog.models.BlogPost.upload_photo_to),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to=blog.models.BlogPost.upload_photo_to),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to=blog.models.BlogPost.upload_photo_to),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo_7',
            field=models.ImageField(blank=True, upload_to=blog.models.BlogPost.upload_photo_to),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo_8',
            field=models.ImageField(blank=True, upload_to=blog.models.BlogPost.upload_photo_to),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='photo_9',
            field=models.ImageField(blank=True, upload_to=blog.models.BlogPost.upload_photo_to),
        ),
    ]
