# Generated by Django 3.1.4 on 2021-01-15 02:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='teaser_blurb',
            field=models.CharField(default='Enter teaser blurb here.', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
