# Generated by Django 5.0.6 on 2024-07-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimages',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
