# Generated by Django 3.1.4 on 2021-01-05 23:31

from django.db import migrations, models
import vehicles.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/self.title'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to=vehicles.models.Vehicles.folder_name),
        ),
    ]
