# Generated by Django 3.1.4 on 2021-01-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20210125_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Semi-auto', 'Semi-auto'), ('CVT', 'CVT'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Gold', 'Gold'), ('Green', 'Green'), ('Grey', 'Grey'), ('Navy', 'Navy'), ('Orange', 'Orange'), ('Red', 'Red'), ('Silver', 'Silver'), ('White', 'White')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Semi-auto', 'Semi-auto'), ('CVT', 'CVT'), ('Other', 'Other')], max_length=100),
        ),
    ]
