# Generated by Django 3.1.4 on 2021-01-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20210129_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(choices=[('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Estate', 'Estate'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Saloon', 'Saloon')], max_length=100),
        ),
    ]
