# Generated by Django 5.0.6 on 2024-07-06 19:59

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_carimages_is_main_carmodel_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='main_image',
            field=models.ForeignKey(blank=True, limit_choices_to={'car_model_id': django.db.models.expressions.OuterRef('pk')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.carimages'),
        ),
    ]
