# Generated by Django 5.0.6 on 2024-07-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_carmodel_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='main_image',
        ),
    ]
