# Generated by Django 3.1.4 on 2021-02-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20210129_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
