# Generated by Django 5.0.6 on 2024-07-06 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_remove_carmodel_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.carimages'),
        ),
    ]
