# Generated by Django 5.0.6 on 2024-07-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_carmodel_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carimages',
            old_name='images',
            new_name='image',
        ),
    ]
